name: Passport Js file

on:
  push:
    branches : [main]

  pull_request:
    branches : [main] 

jobs:
  build:
   runs_on : ubuntu_latest
    steps:
      -uses : actions/checkout@v2
      -name : uses NODE version 16
      -uses : actions/setupnode@v2
        with :
          node_version : '16'
      -run : npm install
      -run : npm run start    
